defaults:
  id: defaultID
  appid: defaultAppID
  certid: defaultCertID

test:
  id:       testID
  devid:    devid
  appid:    appid
  certid:   certid

production:
  id:     productionID
  devid:  productionDevId
  only_production: 3
